#!/usr/bin/env bash
echo "php-cs-fixer pre commit hook start"

PHP_CS_FIXER="bin/php-cs-fixer"
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')
if [ -e .php_cs ]; then
    PHP_CS_CONFIG=".php_cs"
elif [ -e .php_cs.dist ]; then
    PHP_CS_CONFIG=".php_cs.dist"
else
    echo -e "\033[0;31mError: php-cs-fixer config not found\033[0m"
    exit 1
fi
if [ -n "$CHANGED_FILES" ]; then
    $PHP_CS_FIXER fix --config "$PHP_CS_CONFIG" $CHANGED_FILES;
    git add $CHANGED_FILES;
fi

echo -e "\033[0;32mphp-cs-fixer pre commit hook finish\033[0m"
