name: release-sentry

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set release environment
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: List files
      run: ls -la

    - name: Change project version in env file
      working-directory: .
      run: sed -i "" -e "s/^PROJECT_VERSION=.*$/PROJECT_VERSION=${{ env.RELEASE_VERSION }}/" .env.prod
